services:
  booking_db:
    image: postgres:17-alpine
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data_booking:/var/lib/postgresql/data
    networks:
      - booking_network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - booking_db
    networks:
      - booking_network

volumes:
  db_data_booking:

networks:
  booking_network:
